services:
  cpu_playground:
    container_name: cpu_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4000:5432"
    cpus: 0.01
  ram_playground:
    container_name: ram_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4001:5432"
    mem_limit: 150M
  connection_playground:
    container_name: connection_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4002:5432"
  storage_playground:
    container_name: storage_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4003:5432"
    storage_opt:
      size: '1G'
  lwlock_playground:
    container_name: lwlock_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4004:5432"
  timeout_playground:
    container_name: timeout_playground
    build:
      context: playground
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./playground/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4005:5432"
